server:
  port: 8090
  connection-timeout: 120000
spring:
  servlet:
     multipart:
       max-file-size: 2MB
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=yes&characterEncoding=utf8&useSSL=false&&autoReconnect=true&failOverReadOnly=false
      username: root
      password: Hexuantian123
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database: MySQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect